#!/bin/bash
# gen-smoke-list.sh — curate a per-fs smoke list for the tri-fs CI gate.
#
# Recipe (same as the original btrfs smoke.txt): from the confirmed-pass
# universe of the canonical sweep, greedily take the fastest tests that
# each add a not-yet-covered fstests group, so ~20 tests span ~20
# subsystems in about a minute of wall time on 4 slim shards.
#
# Pass universe = tests with an entry in the per-fs times DB (i.e. they
# ran to a verdict) minus raw failures and load-flaky from the canonical
# sweep log, minus the per-fs blacklist and bigmem tier (smoke runs with
# BIG_SHARDS=0, so bigmem tests must not be queued).
#
# CAVEAT: the times DB also carries notrun tests, so pass ARCHIVE= the
# canonical sweep's archived shard dir to subtract its "Not run:" set —
# otherwise fs-unsupported tests (e.g. dedupe/O_TMPFILE on fuse) land in
# the list and trip the gate's strict-notrun check.
#
# Usage: gen-smoke-list.sh xfs|fuse [SWEEPLOG]
#   RESULTS  (default ~/uml-smoke/results)   times DBs, blacklists, groups
#   XFSTESTS (default ~/uml-smoke/xfstests-built)  for xfs/* group info
#   ARCHIVE  archived shard dir of the canonical sweep (notrun harvesting)
#   N        (default 20)  list size; xfs reserves XFS_N (default 7) xfs/* slots
set -euo pipefail
FS="${1:?usage: gen-smoke-list.sh xfs|fuse [sweeplog]}"
RESULTS="${RESULTS:-$HOME/uml-smoke/results}"
XFSTESTS="${XFSTESTS:-$HOME/uml-smoke/xfstests-built}"
N="${N:-20}"; XFS_N="${XFS_N:-7}"
case "$FS" in
  xfs)  SWEEP="${2:-$RESULTS/xfs-sweep-1.log}";;
  fuse) SWEEP="${2:-$RESULTS/fuse-sweep-8.log}";;
  *) echo "unsupported fs: $FS" >&2; exit 1;;
esac
TIMES="$RESULTS/times-db-$FS.txt"

tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

# Tests to exclude: raw failures + load-flaky from the canonical sweep,
# blacklist, bigmem tier.
{ grep '^FAILURES(raw):' "$SWEEP" | tail -1 | cut -d: -f2- | tr ' ' '\n'
  grep '^LOAD-FLAKY' "$SWEEP" | tail -1 | cut -d: -f2- | tr ' ' '\n'
  grep -vE '^#|^\s*$' "$RESULTS/blacklist-$FS.txt" 2>/dev/null
  grep -vE '^#|^\s*$' "$RESULTS/bigmem-$FS.txt" 2>/dev/null
  if [ -n "${ARCHIVE:-}" ]; then
    grep -h '^Not run:' "$ARCHIVE"/*/results/check.log 2>/dev/null \
      | tr ' ' '\n' | grep /
  fi
} | grep . | sort -u > "$tmp/exclude"

# Group map: generic from test-groups.txt, xfs/* from the built tree.
awk '$1 ~ /^generic\//' "$RESULTS/test-groups.txt" > "$tmp/groups"
awk '!/^#/ && NF>1 {printf "xfs/%s", $1; for(i=2;i<=NF;i++) printf " %s", $i; print ""}' \
  "$XFSTESTS/tests/xfs/group.list" >> "$tmp/groups"

# Candidates: (test, time, groups...) for passing tests of the wanted class.
candidates(){ # $1 = test-name prefix regex
  awk -v pfx="$1" 'NR==FNR{t[$1]=$2; next}
    $1 ~ pfx && ($1 in t) {printf "%s %s", $1, t[$1]; for(i=2;i<=NF;i++) printf " %s", $i; print ""}' \
    "$TIMES" "$tmp/groups" | grep -vwFf "$tmp/exclude" | sort -k2 -n
}

# Greedy: fastest first, keep a test only if it covers a new group.
pick(){ # stdin = sorted candidates, $1 = how many
  awk -v want="$1" '{
    fresh=0
    for(i=3;i<=NF;i++) if(!($i in seen)) fresh=1
    if(!fresh) next
    for(i=3;i<=NF;i++) seen[$i]=1
    print $1; if(++n==want) exit
  }'
}

echo "# smoke-$FS.txt — tri-fs CI gate list, generated by gen-smoke-list.sh"
echo "# from $(basename "$SWEEP") + times-db-$FS.txt on $(date +%Y-%m-%d)"
if [ "$FS" = xfs ]; then
  candidates '^xfs/'     | pick "$XFS_N"
  candidates '^generic/' | pick $((N - XFS_N))
else
  candidates '^generic/' | pick "$N"
fi
